### ISSUE TITLE
Wizard/Asistente - PAp

### ISSUE THREAD

**Issue by Luvero-1** [cuervoforjador/conventum#32]
A la hora de la asignación de PAp iniciales:
al aumentar el Incr. de una competencia primaria/paterna lo considera parte de la base por 3 y después la aumenta, ejemplo: 
Base / Incr. / Coste / Final ; 45 / 0 / 0 / 45 ;  54 / 3 / 3 / 57. 
al aumentar el Incr. de una competencia secundaria lo considera parte de la base y después la aumenta, ejemplo:
Base / Incr. / Coste / Final ; 15 / 0 / 0 / 15 ;  16 / 1 / 1 / 17. 

![image1](https://github.com/cuervoforjador/conventum/assets/77019799/4c1e0cc9-801f-4a23-94c1-0938f1cb9bf8)
![image2](https://github.com/cuervoforjador/conventum/assets/77019799/67ef6c5b-4b5b-464b-a554-ea8e5123b806)

**Comment by cuervoforjador** [comment]
Corregido.

En release **2.0.2**

Muchas gracias Luvero !!

**Comment by cuervoforjador** [comment]
Corregido.

En release **2.0.2**

Muchas gracias Luvero !!
