### ISSUE TITLE
Wizard/Asistente - Situación familiar

### ISSUE THREAD

**Issue by Luvero-1** [cuervoforjador/conventum#33]
Una vez en dicha sección del asistente te permite hacer una tirada aleatoria de tus padres pero posteriormente no sale opción de icono de dados para una nueva tirada aleatoria para hermanos y/o cónyuge. La tirada de padres aparece en el chat con normalidad.
![image8](https://github.com/cuervoforjador/conventum/assets/77019799/d77ab2a0-80f5-4f10-be7e-08136d57ab93)

**Comment by cuervoforjador** [comment]
Corregido

En release **2.0.2**

Muchas gracias Luvero!!!
