### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by cuervoforjador** [cuervoforjador/conventum#34]

**Comment by phillipkdick** [comment]
Saludos

Primero agradecerte el haber echo este pack de aquelarre para foundry. Es una currada, visualmente es impresionante. He empezado a pasarme mis aventuras des Roll20 a foundry gracias a tu pack. 

Pero una pequeña duda que tengo es con el hechizo de "Presteza". Es un talisman, que al activarse, da al hechicero, un +20 en iniciativa (que eso se como darlo creando una accion o un hechizo), permite hacer 6 acciones en un turno en vez de 2 (que eso no tengo ni idea de como implementarlo si no es de forma manual en el combat tracker) y cada turno que el talisman esta activo le hace 1 punto de daño al portador (que eso tampoco se como hacerlo)

No se si se podra hacer esa automatizacion en un click

Muchas gracias

Marc

**Comment by cuervoforjador** [comment]
Hola Marc.

El tema de magia por lo general, no es que sea complicado automatizarlo... es que resultaría imposible, ya que cada hechizo es una descripción que no está sujeta a ningún tipo de flujo ni lógica... es lo suyo, puesto que da absoluta libertad para crear hechizos.

Dicho esto,
Existe un modo: **frenético** que al PJ / PNJ que se encuentre en ese modo le permite lanzar todas las acciones que quiera bajo coste 0.

![image](https://github.com/cuervoforjador/conventum/assets/77968758/f57c81e9-5d61-44c1-bad8-ad2eff00190a)

Como DJ, para meter a un personaje en un modo concreto, solo tienes que abrir su ficha, y en **Ver Modos**

![image](https://github.com/cuervoforjador/conventum/assets/77968758/158ce2e5-e9d2-4ac0-b1cd-7f7576632eee)


Busca el modo **Frenético**

![image](https://github.com/cuervoforjador/conventum/assets/77968758/03d8a65e-9b71-47e6-b533-a1a3807202ee)

En ese modo, todas las acciones _"Le salen gratis"_

![image](https://github.com/cuervoforjador/conventum/assets/77968758/c8a43d2a-7a03-4215-8656-ef90f65aaab8)

Deja al PJ que pida acciones... y gestionalas tú como DJ desde el pool de Acciones...

![image](https://github.com/cuervoforjador/conventum/assets/77968758/b94ead7d-7e33-4cb2-90e1-6613c849e9dc)

**Comment by phillipkdick** [comment]
Muchas gracias, me va perfecto
