### ISSUE TITLE
Valores negativos en Competencias y Caracteristicas

### ISSUE THREAD

**Issue by Luvero-1** [cuervoforjador/conventum#35]
Al aplicar un negativo a una competencia o característica que hace que esta pasase a valores negativos se queda automáticamente en 0.

**Comment by cuervoforjador** [comment]
![image](https://github.com/cuervoforjador/conventum/assets/77968758/b4a7352f-9f21-4c17-b96b-f8218e31571d)

Resuelta.
Muchas gracias Luvero...
