### ISSUE TITLE
Idiomas en ficha

### ISSUE THREAD

**Issue by Luvero-1** [cuervoforjador/conventum#37]
Al darle al botón del dado para lanzar una tirada de Idioma (el que sea) desde la pestaña Biografía>Idiomas no lanza tirada alguna

![image](https://github.com/cuervoforjador/conventum/assets/77968758/571e7a16-aa89-4042-9e7b-f7ab483bf9c6)

**Comment by cuervoforjador** [comment]
Corregido.
En realease 2.0.2

Muchas gracias por la info, Luvero!
