### ISSUE TITLE
Detalles biograficos

### ISSUE THREAD

**Issue by Luvero-1** [cuervoforjador/conventum#38]
En la pestaña Biografía>Trasfondo aparece la misma profesión paterna que la del personaje aunque estas sean diferentes
![image7](https://github.com/cuervoforjador/conventum/assets/77019799/4565ef1c-8ff8-4382-a4d0-93ddacbf88dd)
![image9](https://github.com/cuervoforjador/conventum/assets/77019799/80cff652-adbb-4c14-a258-9b9c5c2b1bc8)

**Comment by cuervoforjador** [comment]
Corregido.
Muchas gracias Luvero!
