### ISSUE TITLE
Grimorio - Textos

### ISSUE THREAD

**Issue by Luvero-1** [cuervoforjador/conventum#40]
El scroll lateral y vertical que aparecen al tener un texto considerable en las secciones de Componentes, Efectos, Descripción... es difícil de seleccionar al moverse las hojas del grimorio. ¿Podría hacerse una anchura máxima (el ancho de la hoja del grimorio) para evitar el scroll lateral? Gracias
![image5](https://github.com/cuervoforjador/conventum/assets/77019799/ff55c13e-1b2e-438e-b705-6a4e09ceaf33)

Además el texto de los items Hechizos me salen en latín e ingles
![image1](https://github.com/cuervoforjador/conventum/assets/77019799/45fdc9f3-d2c0-469d-998b-27ad739576ba)
![image2](https://github.com/cuervoforjador/conventum/assets/77019799/d4b606e6-3b35-4cf0-918d-b0c10f85acbc)
![image3](https://github.com/cuervoforjador/conventum/assets/77019799/3dc36a12-d831-4741-b347-fcfa0594bcb2)

**Comment by cuervoforjador** [comment]
Corregido.

Muchas gracias Luvero!
