### ISSUE TITLE
Combat tracker

### ISSUE THREAD

**Issue by Luvero-1** [cuervoforjador/conventum#41]
Durante un combate cuando abres la ventana de encuentros te sale la tirada de iniciativa desde ahí al clicarle la lanza el combat tracker pero para que te salgan reflejadas cada vez que la actualizas de nuevo tienes que cerrar la ventana de encuentros y volver a abrirla, ¿sería posible que esta nueva iniciativa se vira reflejada de forma automática en la ventana de encuentros? Gracias
![image6](https://github.com/cuervoforjador/conventum/assets/77019799/2c8e6c50-931b-4cbb-bc52-c35109f20f2d)

**Comment by cuervoforjador** [comment]
Corregido...

Muchas gracias Luvero.
