### ISSUE TITLE
Modificación de Características mediante Rasgos.

### ISSUE THREAD

**Issue by Bakali77** [cuervoforjador/conventum#43]
Al crear un Rasgo que modifica una Característica (FUE) en +1, se modifica el porcentaje de las Competencias basadas en FUE, pero al hacer tiradas de la Característica, se hacen sobre el valor sin modificar. 

![image](https://github.com/cuervoforjador/conventum/assets/30875600/8647232a-d514-4a26-af55-86d2230f2d06)

**Comment by cuervoforjador** [comment]
Corregido.

![image](https://github.com/cuervoforjador/conventum/assets/77968758/5d06b13b-0cbf-4e5a-88b5-d606db6ff1f1)

Muchas gracias por el apunte.
