### ISSUE TITLE
Rasgos

### ISSUE THREAD

**Issue by phillipkdick** [cuervoforjador/conventum#44]
Edito de 0 el mensaje:

A raiz de hacer los personajes para la campaña he tenido que hacer la tabla entera de rasgos con cada rasgo creado, y he visto que faltan algunos detalles que esos rasgos permitan modificar:

No se puede modificar la IRR o RR
No se puede modificar la Templanza
No se puede modificar el Tamaño y el Peso
No se puede implementar el rasgo "Ambidextro"

A parte, hay rasgos que modifican mas de un caracter y he tenido que  hacer diferentes rasgos para el mismo, por ejemplo. Tuerto 1 (Otorga el -2 de Percepcion), Tuerto 2 (Otorga el -25 a arcos) Tuerto 3... Tuerto 4.... Estaria bien que se pudieran añadir al mismo Rasgo diferentes modificadores.

Por lo demas, no se como exportar esos compendios para subirlos aqui y asi puedas aprovecharlos

**Comment by cuervoforjador** [comment]
Hola Philipp Dick,
Pues lo cierto es que en una primera instancia no se ha valorado hacer los rasgos parametrizables a ese nivel de detalle ya que suponemos que exigiría un esfuerzo que no compensa para un objeto que no suele ser muy recurrente... si solo se aplica una vez en la historia del PJ... 

Es posible que en un futuro nos metamos con ello... pero hasta entonces todo lo que te puedo recomendar es que se creen los rasgos practicamente como literales y a posterior sea el propio director de juego quien modifique ese tipo caracteristicas.

Otra opción "mas técnica" es dejar una "puerta" para que a través de un parametro tipo "systemData.bio.weight + 0.10" se pueda modificar como una inyección directa. Aunque me temo que si ya de por sí el sistema es complejo, esta última opción lo complique mas... 

Lo valoramos!!

Gracias por la nota.
