### ISSUE TITLE
Redondeo en puntos de Concentración y Fé

### ISSUE THREAD

**Issue by Tanynys** [cuervoforjador/conventum#45]
De acuerdo con el manual los Puntos de Concentración son el 20% de la Irracionalidad del personaje redondeando hacia arriba, El sistema calcula el redondeo clásico, menos de 0,5 igual a 0 más de 0,5 igual a 1, con lo que en ocasiones se pierde un punto.

En los Puntos de Fé lo mismo pero con la Racionalidad.

**Comment by cuervoforjador** [comment]
Corregido.
Gracias Tanys.
