### ISSUE TITLE
Bonus por características 

### ISSUE THREAD

**Issue by Tanynys** [cuervoforjador/conventum#47]
Algunos de los bonus de características no se aplican correctamente. He creado un personaje con fuerza 25, habilidad 20 y percepción 10 y no tiene bonus con el hacha de armas, pero tiene 2d6 con cuchillo y ballesta ligera.

**Comment by cuervoforjador** [comment]
![image](https://github.com/cuervoforjador/conventum/assets/77968758/bf721942-b5e0-492e-8656-c98e584bb354)

**Comment by cuervoforjador** [comment]
![image](https://github.com/cuervoforjador/conventum/assets/77968758/e28f421a-7c5f-4284-afad-947af3129ed1)

**Comment by cuervoforjador** [comment]
Corregido.
