### ISSUE TITLE
Creador de personaje

### ISSUE THREAD

**Issue by phillipkdick** [cuervoforjador/conventum#48]
Buenas, es a mi o el creador de pj se ha vuelto loco en el momento de poner las habilidades

Le pongo un +30 en mando

![image](https://github.com/cuervoforjador/conventum/assets/5021282/43aab032-3665-4c0a-8991-329cf7ff8f48)

y cuando se aplica sale esto

![image](https://github.com/cuervoforjador/conventum/assets/5021282/e2c0b05d-34e2-461f-add0-286f5b16323f)

pasa con las primarias y con las paternas, no con las secundarias

**Comment by cuervoforjador** [comment]
Corregido.
En release: **2.0.2**

Muchas gracias por las descripción.
