### ISSUE TITLE
Menús desplegables en la creación de personajes

### ISSUE THREAD

**Issue by Bakali77** [cuervoforjador/conventum#49]
Buenas, haciendo pruebas de creación de personajes, los jugadores, pese a tener los permisos necesarios, no pueden modificar el reino origen, la cultura, la sociedad, estrato social ni la posición.

**Comment by cuervoforjador** [comment]
Hola,

![image](https://github.com/cuervoforjador/conventum/assets/77968758/91f4baeb-ce8c-4b4f-86e0-c08e03877cfe)

En la pantalla inicial del Wizard dejo opciones para que el director de juego decida si el jugador puede o no escoger por si mismo.

Muchas gracias por el feedback.
