### ISSUE TITLE
Errata en la Tabla de Profesiones-Sociedad Islámica-Mercaderes

### ISSUE THREAD

**Issue by Bakali77** [cuervoforjador/conventum#50]
En la Tabla de Profesiones de la sociedad islámica (Mercaderes) hay una errata en el rango Escriba, que debe ser desde el 46 al 55, y está en 46 al 50, creándose un salto del 50 al 55.

![image](https://github.com/cuervoforjador/conventum/assets/30875600/e8136cfa-a868-4bda-bd18-ffc87ce66026)

**Comment by cuervoforjador** [comment]
![image](https://github.com/cuervoforjador/conventum/assets/77968758/cfca343c-7153-4c69-9020-815ce306757d)

Corregido.
Release: **2.0.2**
Muchas gracias por toda la info.
