### ISSUE TITLE
Profesión y Profesión Paterna son la misma

### ISSUE THREAD

**Issue by Xyxorswords** [cuervoforjador/conventum#51]
Creando varios personajes se da la misma circunstancia. Aunque se establece una profesión diferente para el personaje (Sacerdote (Párroco)) y la profesión paterna (Barbero Cirujano) cuando se crea el personaje al final se describe como la misma profesión en el Trasfondo (Sacerdote (Párroco)).
![Captura](https://github.com/cuervoforjador/conventum/assets/75963894/588c31e1-b4a7-426a-923b-3e49094c5dc3)

**Comment by cuervoforjador** [comment]
Corregida 
Release: **2.0.2**
Muchas gracias por las indicaciones.

**Comment by cuervoforjador** [comment]
Corregida
Release: **2.0.2**
Muchas gracias por las indicaciones.
